version: '3'

services:
  fds_postgres:
    image: postgres:14.2-alpine
    container_name: fds_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fds_dev
    ports:
      - '5432:5432'

  fds_django:
    build: .
    container_name: fds_django
    volumes:
      - ./food_delivery_service/:/usr/src/app
    env_file:
      - ./food_delivery_service/.env.dev
    command: python manage.py runserver 0:8000
    ports:
      - '8000:8000'
    depends_on:
      - fds_postgres

volumes:
  postgres_data: {}
