version: '3'

services:
  fds_postgres:
    image: postgres:14.2
    ports:
      - '5432:5432'

  fds_django:
    build: .
    command: python manage.py runserver 0:8000
    ports:
      - '8000:8000'
    depends_on:
      - fds_postgres